Changing to copy to server from pipeline

diff --git a/.github/workflows/Publish-Dnd-server.yml b/.github/workflows/Publish-Dnd-server.yml
--- a/.github/workflows/Publish-Dnd-server.yml
+++ b/.github/workflows/Publish-Dnd-server.yml
@@ -42,54 +42,63 @@ jobs:
           Compress-Archive -Path "$env:LOCAL_PUBLISH_PATH\*" -DestinationPath "$env:LOCAL_PUBLISH_PATH\package.zip"
         shell: pwsh
 
-      - name: Install Web Deploy
-        run: |
-          choco install webdeploy -y
+      # - name: Install Web Deploy
+      #   run: |
+      #     choco install webdeploy -y
 
-      - name: Deploy to IIS via Web Deploy
+      - name: Copy package.zip to server
         shell: pwsh
         env:
           LOCAL_PUBLISH_PATH: ${{ github.workspace }}\publish
         run: |
-          $msdeploy = 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
+          $session = New-PSSession -ComputerName www.tudor-enterprises.com -Credential (New-Object System.Management.Automation.PSCredential("deployuser", (ConvertTo-SecureString "UxXW8gbfJbyrrBlFDNOf" -AsPlainText -Force)))
+          Copy-Item -Path "$env:LOCAL_PUBLISH_PATH\package.zip" -Destination "C:\Program Files\PrimaryServer\Deploy\package.zip" -ToSession $session
+          Remove-PSSession $session
 
-          if (-not (Test-Path $msdeploy)) {
-            Write-Error "msdeploy.exe not found at $msdeploy"
-            exit 1
-          }
+      # - name: Deploy to IIS via Web Deploy
+      #   shell: pwsh
+      #   env:
+      #     LOCAL_PUBLISH_PATH: ${{ github.workspace }}\publish
+      #   run: |
+      #     $msdeploy = 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
 
-          Write-Host "Checking if package exists at $env:LOCAL_PUBLISH_PATH\package.zip"
-          if (-Not (Test-Path "$env:LOCAL_PUBLISH_PATH\package.zip")) {
-          Write-Error "Package file not found!"
-          exit 1
-          }
+      #     if (-not (Test-Path $msdeploy)) {
+      #       Write-Error "msdeploy.exe not found at $msdeploy"
+      #       exit 1
+      #     }
 
-          # Hardcoded credentials
-          $server = "https://www.tudor-enterprises.com:8172/msdeploy.axd?site=PrimaryServer"
-          $site = "PrimaryServer"
-          $user = "deployuser"
-          $pass = "UxXW8gbfJbyrrBlFDNOf"
+      #     Write-Host "Checking if package exists at $env:LOCAL_PUBLISH_PATH\package.zip"
+      #     if (-Not (Test-Path "$env:LOCAL_PUBLISH_PATH\package.zip")) {
+      #     Write-Error "Package file not found!"
+      #     exit 1
+      #     }
 
-          $localPublishPath = $env:LOCAL_PUBLISH_PATH
-          $packagePath = Join-Path $localPublishPath 'package.zip'
-          $sourceArg = "-source:package=`"$packagePath`""
-          $destArg = "-dest:iisApp=`"$site`",computerName=`"$server`",userName=`"$user`",password=`"$pass`",authType=`"Basic`""
+      #     # Hardcoded credentials
+      #     $server = "https://www.tudor-enterprises.com:8172/msdeploy.axd?site=PrimaryServer"
+      #     $site = "PrimaryServer"
+      #     $user = "deployuser"
+      #     $pass = "UxXW8gbfJbyrrBlFDNOf"
 
-          Write-Host "msdeploy path: $msdeploy"
-          Write-Host "source: $sourceArg"
-          Write-Host "dest: $destArg"
+      #     $localPublishPath = $env:LOCAL_PUBLISH_PATH
+      #     $packagePath = Join-Path $localPublishPath 'package.zip'
+      #     $sourceArg = "-source:package=`"$packagePath`""
+      #     $destArg = "-dest:iisApp=`"$site`",computerName=`"$server`",userName=`"$user`",password=`"$pass`",authType=`"Basic`""
 
-          $args = @(
-            '-verb:sync'
-            $sourceArg
-            $destArg
-            '-allowUntrusted'
-            '-verbose'
-          ) 
+      #     Write-Host "msdeploy path: $msdeploy"
+      #     Write-Host "source: $sourceArg"
+      #     Write-Host "dest: $destArg"
 
-          $proc = Start-Process -FilePath $msdeploy -ArgumentList $args -Wait -NoNewWindow -PassThru
+      #     $args = @(
+      #       '-verb:sync'
+      #       $sourceArg
+      #       $destArg
+      #       '-allowUntrusted'
+      #       '-verbose'
+      #     ) 
 
-          if ($proc.ExitCode -ne 0) {
-            Write-Error "msdeploy failed with exit code $($proc.ExitCode)"
-            exit $proc.ExitCode
-          }
+      #     $proc = Start-Process -FilePath $msdeploy -ArgumentList $args -Wait -NoNewWindow -PassThru
+
+      #     if ($proc.ExitCode -ne 0) {
+      #       Write-Error "msdeploy failed with exit code $($proc.ExitCode)"
+      #       exit $proc.ExitCode
+      #     }
